# frozen_string_literal: true

Setting.where(key: "project_singular").first_or_create(var: "project_singular", data_type: "string", label: "NOMBRE DE LA ENTIDAD DEL PRIMER NIVEL", value: "Proyecto")
Setting.where(key: "phase_singular").first_or_create(var: "phase_singular", data_type: "string", label: "NOMBRE DE LA ENTIDAD DEL SEGUNDO NIVEL", value: "Fase")
Setting.where(key: "stage_singular").first_or_create(var: "stage_singular", data_type: "string", label: "NOMBRE DE LA ENTIDAD DEL TERCER NIVEL", value: "Etapa")
Setting.where(key: "lot_singular").first_or_create(var: "lot_singular", data_type: "string", label: "NOMBRE DE LA ENTIDAD DE UNIDAD", value: "Lote")
Setting.where(key: "evo_string").first_or_create(var: "evo_string", data_type: "string", label: "ESTRUCTURA EVO", value: "EVO")
Setting.where(key: "referent_commission").first_or_create(var: "referent_commission", data_type: "percentage", label: "COMISION POR REFERIDO", value: 0)
Setting.where(key: "payment_due_soon").first_or_create(var: "payment_due_soon", data_type: "csv", label: "ENVIO DE RECORDATORIO: PAGO", value: "15,5")
Setting.where(key: "link_expiration_for_subscriptions").first_or_create(var: "link_expiration_for_subscriptions", data_type: "integer", label: "VENCIMIENTO DE ENLACES: SUSCRIPCIONES (horas)", value: "24")
Setting.where(key: "card_soon_to_expire").first_or_create(var: "card_soon_to_expire", data_type: "csv", label: "ENVIO DE RECORDATORIO: ACTUALIZACION DE TARJETAS", value: "1,15")
Setting.where(key: "link_expiration_for_card_expire").first_or_create(var: "link_expiration_for_card_expire", data_type: "integer", label: "VENCIMIENTO DE ENLACES: ACTUALIZACION DE TARJETAS (horas)", value: "24")
Setting.where(key: "subscription_soon_to_finish").first_or_create(var: "subscription_soon_to_finish", data_type: "csv", label: "ENVIO DE RECORDATORIO: FINALIZACION DE SUSCRIPCION", value: "1,15")
Setting.where(key: "inbound_penalty").first_or_create(var: "inbound_penalty", concept: "commission", data_type: "percentage", label: "PENALIZACION POR VENTA INBOUND", value: "0")
Setting.where(key: "marketing_commission").first_or_create(var: "marketing_commission", concept: "commission", data_type: "percentage", label: "COMISION POR MARKETING (SUBDIRECTOR)", value: "0")
Setting.where(key: "extra_realtor_follow_up_commission").first_or_create(var: "extra_realtor_follow_up_commission", concept: "commission", data_type: "percentage", label: "COMISION EXTRA POR SEGUIMIENTO DE INMOBILIARIA", value: "0")
Setting.where(key: "accept_email_step_id").first_or_create(var: "accept_email_step_id", data_type: "integer", label: "ENVIO DE CORREO: ID de paso para envio de notificación", value: "0")
Setting.where(key: "expired_lifetime").first_or_create(var: "expired_lifetime", data_type: "integer", label: "TIEMPO DE VIDA DE EXPIRADOS EN DIAS", value: "5")
Setting.where(key: "expired_notification_emails").first_or_create(var: "expired_notification_emails", data_type: "csv", label: "ENVIO DE NOTIFICACIÓN: EXPIRACIONES", value: "")
Setting.where(key: "step_column_max_request_rows").first_or_create(var: "step_column_max_request_rows", data_type: "integer", label: "CANTIDAD MAXIMA DE REGISTROS POR SOLICITUD EN LOS PASOS DEL PIPELINE", value: "10")
Setting.where(key: "subscription_webhook").first_or_create(var: "subscription_webhook", data_type: "boolean", label: "WEBHOOK PARA CONCILIACIONES AUTOMÁTICAS", value: "false")
Setting.where(key: "phone").first_or_create(var: "phone", data_type: "string", label: "TELÉFONO PRINCIPAL DE LA COMPAÑIA", value: "9999139999")
Setting.where(key: "home-page").first_or_create(var: "home-page", data_type: "string", label: "PAGINA PRINCIPAL DE LA COMPAÑIA", value: "http://example.com")
Setting.where(key: "privacy-policy").first_or_create(var: "privacy-policy", data_type: "string", label: "LINK DE POLITICA DE PRIVACIDAD", value: "http://example.com/pricacy-policy")
Setting.where(key: "company-name").first_or_create(var: "company-name", data_type: "string", label: "NOMBRE DE LA COMPAÑIA", value: "NOMBRE COMPAÑIA")
Setting.where(key: "use_quote_select").first_or_create(var: "use_quote_select", data_type: "boolean", label: "Utilizar listado de cotizaciones en cotizador", value: "false")
Setting.where(key: "single_page_pld").first_or_create(var: "single_page_pld", data_type: "boolean", label: "Utiliza el formato de una página para el anexo PLD", value: "false")
Setting.where(key: "download_limit").first_or_create(var: "download_limit", data_type: "integer", label: "Etiqueta para establecer un limite de datos descargados", value: "10000")
Setting.where(key: "smaller_amortization_table").first_or_create(var: "smaller_amortization_table", data_type: "boolean", label: "La tabla de amortización usará la mitad de tamaño, cabiendo así 2 tablas por hoja.", value: "false")
Setting.where(key: "slack_subscription_notifs_hook").first_or_create(var: "slack_subscription_notifs_hook", data_type: "string", label: "Webhook de Slack para publicar errores en la recepción de pagos de suscripciones", value: "")
Setting.where(key: "client_confirmation").first_or_create(var: "client_confirmation", data_type: "boolean", label: "Confirmación de correos de clientes", value: "false")
Setting.where(key: "automatic_cash_back_payment_method_id").first_or_create(var: "automatic_cash_back_payment_method_id", data_type: "integer", label: "Metodo de pago de bonificación automatica", value: "0")
Setting.where(key: "automatic_cash_back_amount").first_or_create(var: "automatic_cash_back_amount", data_type: "float", label: "Monto de bonificación automatica", value: "0")
