# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  encryption_phrase: ABCD:EFGH
  secret_key_base: ee43a3fbddfd80eb9e594c78b51d87c93dc61fce9430ffc44f2cbb0a3be1b3b7ce89c13277574d4fc1144d918ba1d6a7eaefb32a904e04cf91f24d66d685e71a
  secret_payment: 24d66d685e718b51d87cf2cbb0a3be1b3b7ce89c1144d918ba1d6a7eaefb32a904ea13277eb9e594ce04cf91f5747e43a3fbddf93dc61fce9d4fc430ffc44d80
  api_key_base: xSc9oSmpgjH+1wjZNEgoFNwpNaESTxRE
  encryption_key: asdasd67as6d7as7d6as7da7s6dasdadsa67d8sa6da7s8d6a7ds67ad67a6ds6ddasd
  mailer_address: <%= ENV["MAILER_ADDRES"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  paypal_client_id: Aa3pfQeaJizoUHljKGhbJz7hTKTzGe2kqbpia4_5ZOxJEdCanPF-J5Fg51gTvd-Xq5kMzk04aGcW-gT_
  paypal_client_secret: EPDL2udBUOcjo5Aiy0VUtYLCwxgnDLdB6jJFBMhzBO60P-cYhBovLzMWHTBgmMQK8_OsEUJNTwIMPla1
  paypal_mode: sandbox
  hubspot_apikey: 164ee323-4fa3-44bb-8fcd-fb412669c6a3
  hubspot_pipeline: "default"
  hubspot_appointmentscheduled: "appointmentscheduled"
  hubspot_closedwon: "closedwon"
  hubspot_closedlost: "closedlost"
  hotjar_id: "1863711"
  tinymce_key: "z0ikp7jyyyg8slyc4ovdqdgrlfwitjzqwnm0da045yne38qu"
  tinymce_type: "premium"
  app_emailer: "Adara CRM <no-responder@ejemplo.com>"
  twilio_account_sid: XXXXXXXXXXXXXXXXXXXXXXXXXX
  twilio_auth_token: XXXXXXXXXXXXXXXXXXXXXXXXXX
  phone_number: "+521234567890"
  bitly_token: XXXXXXXXXXXXXXXXXXXXXXXXXX
  bugsnag: 'development'
  encryption_key: '5DCC67393750523CD165F17E1EFADD21'
  fixed_chain: 'SNDBX123'
  id_company: 'SNBX'
  id_branch: '01SNBXBRNCH'
  user: 'SNBXUSR01'
  pwd: 'SECRETO'

test:
  encryption_phrase: ABCD:EFGH
  secret_key_base: 454bbdcacd5a0b74a95aaf1cbc9ff788ae285ecd48d62d8bd739ca60fb67a011ca9d3050e52353b7ab15286bd5e372828517f413211bacb12d6ba60ad307ee3a
  secret_payment: <%= ENV["SECRET_PAYMENT"] %>
  api_key_base: xSc9oSmpgjH+1wjZNEgoFNwpNaESTxRE
  encryption_key: <%= ENV["ENCRYPTION_KEY"] %>
  mailer_address: <%= ENV["MAILER_ADDRES"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  paypal_client_id: Aa3pfQeaJizoUHljKGhbJz7hTKTzGe2kqbpia4_5ZOxJEdCanPF-J5Fg51gTvd-Xq5kMzk04aGcW-gT_
  paypal_client_secret: EPDL2udBUOcjo5Aiy0VUtYLCwxgnDLdB6jJFBMhzBO60P-cYhBovLzMWHTBgmMQK8_OsEUJNTwIMPla1
  paypal_mode: sandbox
  hubspot_apikey: 164ee323-4fa3-44bb-8fcd-fb412669c6a3
  hubspot_pipeline: "default"
  hubspot_appointmentscheduled: <%= ENV["HUBSPOT_APPOINTMENTSCHEDULED"] %>
  hubspot_closedwon: <%= ENV["HUBSPOT_CLOSEDWON"] %>
  hubspot_closedlost: <%= ENV["HUBSPOT_CLOSEDLOST"] %>
  hotjar_id: <%= ENV["HOTJAR_ID"] %>
  tinymce_key: <%= ENV["TINYMCE_KEY"] %>
  tinymce_type: <%= ENV["TINYMCE_TYPE"] %>
  app_emailer: "Adara CRM <no-responder@ejemplo.com>"
  twilio_account_sid: XXXXXXXXXXXXXXXXXXXXXXXXXX
  twilio_auth_token: XXXXXXXXXXXXXXXXXXXXXXXXXX
  phone_number: "+521234567890"
  bitly_token: <%= ENV["BITLY_TOKEN"] %>
  encryption_key: '5DCC67393750523CD165F17E1EFADD21'
  fixed_chain: 'SNDBX123'
  id_company: 'SNBX'
  id_branch: '01SNBXBRNCH'
  user: 'SNBXUSR01'
  pwd: 'SECRETO'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  encryption_phrase: ABCD:EFGH
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_payment: <%= ENV["SECRET_PAYMENT"] %>
  api_key_base: <%= ENV["API_KEY_BASE"] %>
  encryption_key: <%= ENV["ENCRYPTION_KEY"] %>
  mailer_address: <%= ENV["MAILER_ADDRES"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  paypal_client_secret: <%= ENV["PAYPAL_CLIENT_SECRET"] %>
  paypal_mode: <%= ENV["PAYPAL_MODE"] %>
  hubspot_apikey: <%= ENV["HUBSPOT_APIKEY"] %>
  hubspot_pipeline: <%= ENV["HUBSPOT_PIPELINE"] %>
  hubspot_appointmentscheduled: <%= ENV["HUBSPOT_APPOINTMENTSCHEDULED"] %>
  hubspot_closedwon: <%= ENV["HUBSPOT_CLOSEDWON"] %>
  hubspot_closedlost: <%= ENV["HUBSPOT_CLOSEDLOST"] %>
  hotjar_id: <%= ENV["HOTJAR_ID"] %>
  tinymce_key: <%= ENV["TINYMCE_KEY"] %>
  tinymce_type: <%= ENV["TINYMCE_TYPE"] %>
  scount_key: <%= ENV["SCOUT_KEY"] %>
  scount_log_level: <%= ENV["SCOUT_LOG_LEVEL"] %>
  scount_monitor: <%= ENV["SCOUT_MONITOR"] %>
  app_emailer: <%= ENV["APP_EMAILER"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
  bitly_token: <%= ENV["BITLY_TOKEN"] %>
  bugsnag: <%= ENV["BUGSNAG_KEY"] %>
